/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IIntellisenseHub, IIntellisenseReceiver } from './CodeApi.Hubs';
import type { IntellisenseTextRequest } from '../CodeApi.Models.Intellisense.Requests';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IIntellisenseHub"): HubProxyFactory<IIntellisenseHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IIntellisenseHub") {
        return IIntellisenseHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IIntellisenseReceiver"): ReceiverRegister<IIntellisenseReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IIntellisenseReceiver") {
        return IIntellisenseReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IIntellisenseHub_HubProxyFactory implements HubProxyFactory<IIntellisenseHub> {
    public static Instance = new IIntellisenseHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IIntellisenseHub => {
        return new IIntellisenseHub_HubProxy(connection);
    }
}

class IIntellisenseHub_HubProxy implements IIntellisenseHub {

    public constructor(private connection: HubConnection) {
    }
}


// Receiver

class IIntellisenseReceiver_Binder implements ReceiverRegister<IIntellisenseReceiver> {

    public static Instance = new IIntellisenseReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IIntellisenseReceiver): Disposable => {

        const __requestCompletions = (...args: [IntellisenseTextRequest]) => receiver.requestCompletions(...args);

        connection.on("RequestCompletions", __requestCompletions);

        const methodList: ReceiverMethod[] = [
            { methodName: "RequestCompletions", method: __requestCompletions }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

