@CodeApi_HostAddress = http://localhost:5189

### Hello World
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.WriteLine(\"Hello, world!\");"
}

### Syntax Error
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.WriteLine(\"OOPS\");"
}

### Timeout (~10s)
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "await Task.Delay(11000);"
}

### Large Output Truncation
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.Write(new string('a', 1100000));"
}

### Syntax Error
POST {{CodeApi_HostAddress}}/api/completions/
Content-Type: application/json

{
  "code": "Console.WriteLine(\"OOPS\");",
  "lineNumber": "1",
  "column": "1"
}