@CodeApi_HostAddress = http://localhost:5189

### Hello World
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.WriteLine(\"Hello, world!\");"
}

### Syntax Error
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.WriteLine(\"OOPS\");"
}

### Timeout (~10s)
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "await Task.Delay(11000);"
}

### Large Output Truncation
POST {{CodeApi_HostAddress}}/api/exec/run
Content-Type: application/json

{
  "code": "Console.Write(new string('a', 1100000));"
}

### Syntax Error
POST {{CodeApi_HostAddress}}/api/completions/
Content-Type: application/json

{
  "code": "Console.WriteLine(\"OOPS\");",
  "lineNumber": "1",
  "column": "1"
}

POST http://localhost:5189/hubs/intellisense/negotiate?negotiateVersion=1
Content-Type: application/json


### SignalR Hub w/ postman
// new "WebSocket"
// "localhost:5189/hubs/intellisense"
// first message:
// {"protocol": "json","version": 1}
// second message:
// {"type":1,"target":"requestCompletions","arguments":[{"doc": {"sessionId":"91d152f3bd4644db98dfd66e9cad5dc9","languageVersion":"C#14"},"text":{"content":"Guid.","cursorOffset":5}}]}
