/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from CodeApi.Models.Intellisense.AppCompletionItem */
export type AppCompletionItem = {
    /** Transpiled from string */
    displayText: string;
    /** Transpiled from string */
    kind: string;
    /** Transpiled from string? */
    filterText?: string;
    /** Transpiled from string? */
    sortText?: string;
    /** Transpiled from string */
    insertText: string;
    /** Transpiled from CodeApi.Models.Intellisense.InsertTextFormat */
    insertTextFormat?: InsertTextFormat;
    /** Transpiled from string? */
    documentation?: string;
}

/** Transpiled from CodeApi.Models.Intellisense.DocumentRef */
export type DocumentRef = {
    /** Transpiled from string */
    sessionId: string;
    /** Transpiled from string */
    languageVersion: string;
}

/** Transpiled from CodeApi.Models.Intellisense.InsertTextFormat */
export enum InsertTextFormat {
    PlainText = 1,
    Snippet = 2,
}

/** Transpiled from CodeApi.Models.Intellisense.TextState */
export type TextState = {
    /** Transpiled from string */
    content: string;
    /** Transpiled from int */
    cursorOffset: number;
}

