/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { AppCompletionItem } from './CodeApi.Models.Intellisense';

/** Transpiled from CodeApi.Hubs.CompletionsResponse */
export type CompletionsResponse = {
    /** Transpiled from System.Collections.Generic.IReadOnlyList<CodeApi.Models.Intellisense.AppCompletionItem> */
    items: AppCompletionItem[];
}

