/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { DocumentRef, TextState } from './CodeApi.Models.Intellisense';

/** Transpiled from CodeApi.Models.Intellisense.Requests.IntellisenseTextRequest */
export type IntellisenseTextRequest = {
    /** Transpiled from CodeApi.Models.Intellisense.DocumentRef */
    doc: DocumentRef;
    /** Transpiled from CodeApi.Models.Intellisense.TextState */
    text: TextState;
}

